<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
<!--      
	<property>
    	<name>dfs.write.packet.size</name>
    	<value>6553600</value>
  	</property> -->
    <property>
    	<name>dfs.support.append</name>
    	<value>true</value>
  	</property>
  	<property>
    	<name>dfs.replication</name>
    	<value>3</value>
  	</property>
  	<property>
    	<name>dfs.blocksize</name>
    	<value>67108864</value>
   	</property>
    <property>
    	<name>dfs.datanode.socket.write.timeout</name>
    	<value>3600000</value>
  	</property>
  	<property>
    	<name>dfs.socket.timeout</name>
    	<value>3600000</value>
  	</property>
  	<property>
    	<name>fs.defaultFS</name>
    	<value>hdfs://cloudgis</value>
  	</property>
  	
  	
  	<property>
    	<name>dfs.nameservices</name>
    	<value>cloudgis</value>
  	</property>
  	
  	<property>
    	<name>dfs.ha.namenodes.cloudgis</name>
    	<value>nn1,nn2</value>
  	</property>
  	
  	
  	<property>
    	<name>dfs.namenode.rpc-address.cloudgis.nn1</name>
    	<value>cloudgis1.com:8020</value>
  	</property>
  	
  	
  	<property>
    	<name>dfs.namenode.rpc-address.cloudgis.nn2</name>
    	<value>cloudgis2.com:8020</value>
  	</property>
	<property>
    	<name>dfs.client.failover.proxy.provider.cloudgis</name>
    	<value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
  	</property>
  	
</configuration>